<a href="https://colab.research.google.com/github/imamfirdaus-if/Mental-Health-on-Tech-Workplaces/blob/main/treatment_workers_in_the_tech_workplace_who_experience_mental_health_disorders.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### Analisis Pengaruh Pemberian Perawatan Kesehatan Mental pada Pekerja di Industri Teknologi terhadap Kesehatan Mental menggunakan Algoritma Naive Bayes (Studi kasus: Pekerja Industri Teknologi di Amerika Serikat)


In [ ]:
import pandas as pd
import numpy as np

In [ ]:
# input data
mentalhealth=pd.read_excel("DataModelling-survey-mental-health-on-tech-workplaces.xlsx")
# Menampilkan data
mentalhealth.head()

Age  Gender  self_employed  family_history  treatment  work_interfere  \
0   18       1              3               3          4              11   
1   18       1              3               3          4               9   
2   18       1              3               3          3              10   
3   19       1              3               3          3               9   
4   20       1              3               3          3              10   

   3_employees  remote_work  tech_company  benefits  ...  a3nymity  leave  \
0           16            4             4         3  ...         4     22   
1           17            3             4         5  ...         5      5   
2           18            3             4         5  ...         5     22   
3           16            3             4         5  ...         5      5   
4           18            3             4         5  ...         5      5   

   mental_health_consequence  phys_health_consequence  coworkers  supervisor  \
0                          3                        3          8           3   
1                          4                        3          3           3   
2                          3                        3          8           8   
3                          3                        3          8           4   
4                          3                        3          8           4   

   mental_health_interview  phys_health_interview  mental_vs_physical  \
0                        3                      3                   5   
1                        3                      7                   5   
2                        3                      7                   4   
3                        7                      7                   5   
4                        7                      7                   4   

   obs_consequence  
0                3  
1                3  
2                3  
3                3  
4                3  

[5 rows x 23 columns]

In [ ]:
# menampilkan informasi data
mentalhealth.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 601 entries, 0 to 600
Data columns (total 23 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   Age                        601 non-null    int64
 1   Gender                     601 non-null    int64
 2   self_employed              601 non-null    int64
 3   family_history             601 non-null    int64
 4   treatment                  601 non-null    int64
 5   work_interfere             601 non-null    int64
 6   3_employees                601 non-null    int64
 7   remote_work                601 non-null    int64
 8   tech_company               601 non-null    int64
 9   benefits                   601 non-null    int64
 10  care_options               601 non-null    int64
 11  wellness_program           601 non-null    int64
 12  seek_help                  601 non-null    int64
 13  a3nymity                   601 non-null    int64
 14  leave                     

In [ ]:
# Mengecek apakah ada deret yang kosong
mentalhealth.empty

False

In [ ]:
# Melihat ukuran dari data
mentalhealth.size

13823

In [ ]:
# Variabel independen
x = mentalhealth.drop(["treatment"], axis = 1)
x.head()

Age  Gender  self_employed  family_history  work_interfere  3_employees  \
0   18       1              3               3              11           16   
1   18       1              3               3               9           17   
2   18       1              3               3              10           18   
3   19       1              3               3               9           16   
4   20       1              3               3              10           18   

   remote_work  tech_company  benefits  care_options  ...  a3nymity  leave  \
0            4             4         3             3  ...         4     22   
1            3             4         5             3  ...         5      5   
2            3             4         5             6  ...         5     22   
3            3             4         5             6  ...         5      5   
4            3             4         5             6  ...         5      5   

   mental_health_consequence  phys_health_consequence  coworkers  supervisor  \
0                          3                        3          8           3   
1                          4                        3          3           3   
2                          3                        3          8           8   
3                          3                        3          8           4   
4                          3                        3          8           4   

   mental_health_interview  phys_health_interview  mental_vs_physical  \
0                        3                      3                   5   
1                        3                      7                   5   
2                        3                      7                   4   
3                        7                      7                   5   
4                        7                      7                   4   

   obs_consequence  
0                3  
1                3  
2                3  
3                3  
4                3  

[5 rows x 22 columns]

In [ ]:
# Variabel dependen
y = mentalhealth["treatment"]
y.head()

0    4
1    4
2    3
3    3
4    3
Name: treatment, dtype: int64

In [ ]:
# Import train_test_split function
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.2, random_state = 123)

In [ ]:
# Import Gaussian Naive Bayes model
from sklearn.naive_bayes import GaussianNB
# Mengaktifkan/memanggil/membuat fungsi klasifikasi Naive bayes
modelnb = GaussianNB()
# Memasukkan data training pada fungsi klasifikasi naive bayes
nbtrain = modelnb.fit(x_train, y_train)
nbtrain.class_count_

array([216., 264.])

In [ ]:
# Menentukan hasil prediksi dari x_test
y_pred = nbtrain.predict(x_test)
y_pred

array([4, 3, 4, 4, 3, 3, 4, 4, 3, 4, 4, 4, 3, 3, 4, 3, 4, 3, 4, 4, 4, 3,
       4, 4, 4, 4, 3, 3, 3, 4, 4, 3, 4, 3, 3, 4, 4, 4, 3, 4, 4, 3, 3, 4,
       3, 4, 4, 4, 4, 3, 4, 3, 4, 4, 4, 3, 3, 4, 4, 4, 3, 4, 4, 4, 4, 3,
       4, 4, 4, 4, 3, 3, 4, 3, 4, 3, 4, 4, 4, 3, 3, 4, 4, 4, 4, 4, 4, 4,
       4, 4, 4, 3, 4, 4, 4, 4, 4, 3, 4, 3, 3, 4, 4, 4, 4, 4, 4, 4, 4, 3,
       4, 4, 3, 3, 3, 3, 3, 4, 4, 4, 4])

In [ ]:
# Menentukan probabilitas hasil prediksi
nbtrain.predict_proba(x_test)

array([[6.46034147e-02, 9.35396585e-01],
       [1.00000000e+00, 3.72885166e-23],
       [6.23026716e-03, 9.93769733e-01],
       [4.51835374e-02, 9.54816463e-01],
       [1.00000000e+00, 1.35350834e-23],
       [1.00000000e+00, 2.65796675e-23],
       [2.44509511e-04, 9.99755490e-01],
       [3.35979981e-03, 9.96640200e-01],
       [1.00000000e+00, 3.61767676e-22],
       [4.64470006e-03, 9.95355300e-01],
       [1.01449034e-01, 8.98550966e-01],
       [4.65159124e-02, 9.53484088e-01],
       [6.75132933e-01, 3.24867067e-01],
       [5.40483682e-01, 4.59516318e-01],
       [1.43565334e-01, 8.56434666e-01],
       [1.00000000e+00, 3.37056190e-22],
       [1.24513433e-01, 8.75486567e-01],
       [1.00000000e+00, 7.21604691e-22],
       [3.02598298e-01, 6.97401702e-01],
       [1.48431463e-02, 9.85156854e-01],
       [2.16133677e-02, 9.78386632e-01],
       [1.00000000e+00, 3.00673009e-20],
       [2.56193724e-02, 9.74380628e-01],
       [2.47659053e-01, 7.52340947e-01],
       [4.772712

In [ ]:
# import confusion_matrix model
from sklearn.metrics import confusion_matrix
confusion_matrix(y_test, y_pred)

array([[32, 22],
       [ 9, 58]])

In [ ]:
# Menghitung nilai akurasi dari klasifikasi naive bayes 
from sklearn.metrics import classification_report
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           3       0.78      0.59      0.67        54
           4       0.72      0.87      0.79        67

    accuracy                           0.74       121
   macro avg       0.75      0.73      0.73       121
weighted avg       0.75      0.74      0.74       121

